# Generated by Django 5.0.6 on 2026-06-10 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('input_value', models.CharField(max_length=2048)),
                ('normalized_url', models.CharField(blank=True, max_length=2048, null=True)),
                ('domain', models.CharField(blank=True, max_length=512, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=128, null=True)),
                ('risk_score', models.IntegerField(default=0)),
                ('threat_level', models.CharField(choices=[('Safe', 'Safe'), ('Suspicious', 'Suspicious'), ('Dangerous', 'Dangerous')], max_length=20)),
                ('confidence', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=10)),
                ('summary', models.TextField(blank=True, null=True)),
                ('recommendation', models.TextField(blank=True, null=True)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-scanned_at'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_rating', models.CharField(choices=[('helpful', 'helpful'), ('not_helpful', 'not_helpful'), ('false_positive', 'false_positive'), ('false_negative', 'false_negative')], max_length=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='api.scan')),
            ],
        ),
        migrations.CreateModel(
            name='ScanSignal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('signal_name', models.CharField(max_length=128)),
                ('severity', models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high'), ('critical', 'critical')], max_length=20)),
                ('points', models.IntegerField()),
                ('explanation', models.TextField()),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='api.scan')),
            ],
        ),
        migrations.CreateModel(
            name='ThreatApiResult',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('clean', 'clean'), ('malicious', 'malicious'), ('suspicious', 'suspicious'), ('error', 'error'), ('skipped', 'skipped')], max_length=32)),
                ('raw_summary', models.TextField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_results', to='api.scan')),
            ],
        ),
    ]
