export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}"
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#0e1416",
        "on-tertiary-fixed-variant": "#643f00",
        "surface-container-highest": "#2f3638",
        "outline": "#859397",
        "on-primary-container": "#005763",
        "error-container": "#93000a",
        "on-primary-fixed": "#001f25",
        "surface-container-low": "#161d1e",
        "on-primary": "#00363e",
        "secondary": "#bec6e0",
        "surface-dim": "#0e1416",
        "inverse-surface": "#dde4e5",
        "secondary-fixed-dim": "#bec6e0",
        "on-error-container": "#ffdad6",
        "error": "#ffb4ab",
        "tertiary-container": "#ffb13b",
        "inverse-primary": "#006877",
        "surface-container-lowest": "#090f11",
        "on-primary-fixed-variant": "#004e5a",
        "primary-fixed": "#a2eeff",
        "on-secondary-fixed-variant": "#3f465c",
        "tertiary": "#ffd6a3",
        "on-secondary": "#283044",
        "surface-container": "#1a2122",
        "on-tertiary-fixed": "#2a1800",
        "on-surface": "#dde4e5",
        "on-secondary-fixed": "#131b2e",
        "tertiary-fixed-dim": "#ffb957",
        "on-tertiary": "#462b00",
        "on-tertiary-container": "#6e4600",
        "primary-fixed-dim": "#2fd9f4",
        "secondary-fixed": "#dae2fd",
        "on-secondary-container": "#adb4ce",
        "on-background": "#dde4e5",
        "surface-bright": "#343a3c",
        "primary": "#8aebff",
        "surface-container-high": "#242b2d",
        "on-surface-variant": "#bbc9cd",
        "surface-variant": "#2f3638",
        "secondary-container": "#3f465c",
        "on-error": "#690005",
        "outline-variant": "#3c494c",
        "background": "#0e1416",
        "surface-tint": "#2fd9f4",
        "inverse-on-surface": "#2b3233",
        "primary-container": "#22d3ee",
        "tertiary-fixed": "#ffddb5"
      },
      spacing: {
        "stack-md": "16px",
        "stack-sm": "8px",
        "stack-lg": "32px",
        "container-padding": "24px",
        "unit": "4px",
        "gutter": "16px"
      },
      fontFamily: {
        "display-lg": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-caps": ["Geist", "monospace"],
        "headline-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "data-mono": ["Geist", "monospace"]
      },
      fontSize: {
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.1em", "fontWeight": "600" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "headline-sm": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "data-mono": ["14px", { "lineHeight": "20px", "letterSpacing": "0.02em", "fontWeight": "500" }]
      }
    }
  },
  plugins: []
}
